### ISSUE TITLE
Convert SQL database from SQLite to PostgreSQL

### ISSUE THREAD

**Issue by EngineerRandyN** [EngineerRandyN/MRPHero#99]
Main reason is due to the fact that we are unable to use SQLite concurrently with multiple users. Its main intention is for embedded devices that would have a single process/user using it. PostgreSQL enables us to have concurrency aligned with ACID.

**Comment by Nanofu** [comment]
Ohh that's good to know. I was wondering how we can demonstrate how to show him concurrency of a manager and employee accessing the database. Would it require us to change a lot of our code right now?

**Comment by EngineerRandyN** [comment]
We do it by opening two instances of the app

**Comment by Nanofu** [comment]
Ah ok, so switching over to PostgreSQL. What is the steps for getting it done?

**Comment by EngineerRandyN** [comment]
Instead of using SQLite's specific functions, we just use PostgreSQL's. Merely the same, but better to migrate now than later.

**Comment by EngineerRandyN** [comment]
It's almost identical, but will take some time to migrate.

**Comment by tlei1217** [comment]
Cool. Do we have to download it because I saw the download page?

**Comment by EngineerRandyN** [comment]
As a devtool, yes. It downloads the database viewer which lets us edit it.

**Comment by EngineerRandyN** [comment]
Decision is that this is just a demonstration app and by no means will be used in a real environment.
